Transclusion Enhancments
oleeskild/obsidian-digital-garden pull request #141
Opened 2023-01-05 17:48 UTC by uroybd

This PR implements 2 things:
  1. Transcluded block signature to id.
  2. Link in embedded section for header and block transclusion.

2023-01-05 20:25 UTC, oleeskild requested changes

2023-01-05 20:25 UTC, oleeskild commented on package.json
> +        "@sindresorhus/slugify": "^2.1.1",
Ufortunately the 2.*.* version of this library uses some node specific APIs, meaning the plugin breaks on mobile devices. So this needs to stay version 1.1.0.

2023-01-05 20:25 UTC, oleeskild commented on src/Publisher.ts
> +		const published_files = await this.getFilesMarkedForPublishing();
Can this be changed to camelCase to adhere to the convention in the project?
```suggestion
		const publishedFiles = await this.getFilesMarkedForPublishing();
```

2023-01-05 20:25 UTC, oleeskild commented on src/Publisher.ts
> +						if (published_files.find((f) => f.path == linkedFile.path)) {
```suggestion
						if (publishedFiles.find((f) => f.path == linkedFile.path)) {
```

2023-01-06 05:48 UTC, uroybd commented
Done the changes based on the review. :smile:

2023-01-06 07:37 UTC, oleeskild reviewed
Awesome! One last thing: remove the console.log statement. After that, I will merge it 😄

2023-01-06 07:37 UTC, oleeskild commented on src/Publisher.ts
> +        console.log(text);
```suggestion
```

2023-01-06 07:41 UTC, oleeskild approved these changes

2023-01-06 07:51 UTC, merged